/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZP_ZSOR_HDRListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZP_ZSOR_HDRList.iSeeThisPage();
        });


        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZP_ZSOR_HDRList.onTable().iCheckColumns(undefined, {"Sor":{"header":"Sales Order Request"},"Vbeln":{"header":"Sales Document"},"Bukrs":{"header":"Company Code"},"Kunag":{"header":"Sold-to Party"},"Kunwe":{"header":"Ship-to Party"},"Vkorg":{"header":"Sales Organization"},"Vtweg":{"header":"Distribution Channel"},"Spart":{"header":"Division"},"Netwr":{"header":"Net Value"},"Waerk":{"header":"Document Currency"},"Bstkd":{"header":"Customer Reference"},"Soldtoadrnr":{"header":"Sold-To Address"},"Shiptoadrnr":{"header":"Ship-to address"},"Contract":{"header":"SD Document"},"Quote":{"header":"SD Document"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZP_ZSOR_HDRList.onFilterBar().iExecuteSearch();
            
            Then.onTheZP_ZSOR_HDRList.onTable().iCheckRows();

            When.onTheZP_ZSOR_HDRList.onTable().iPressRow(0);
            Then.onTheZP_ZSOR_HDRObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});