/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZP_ZSOR_ITMObjectPageObjectPage journey");

        opaTest("Navigate to ZP_ZSOR_ITMObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZP_ZSOR_HDRList.onFilterBar().iExecuteSearch();

            Then.onTheZP_ZSOR_HDRList.onTable().iCheckRows();
            When.onTheZP_ZSOR_HDRList.onTable().iPressRow(0);

            Then.onTheZP_ZSOR_HDRObjectPage.iSeeThisPage();
            Then.onTheZP_ZSOR_HDRObjectPage.onTable({ property: "_Items" }).iCheckRows();
            When.onTheZP_ZSOR_HDRObjectPage.onTable({ property: "_Items" }).iPressRow(0);

            Then.onTheZP_ZSOR_ITMObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZP_ZSOR_ITMObjectPage.iCheckSection({ section: "itemgeninfo" });
            Then.onTheZP_ZSOR_ITMObjectPage.onForm({ section: "itemgeninfo" }).iCheckField({ property: "Matnr" });
            Then.onTheZP_ZSOR_ITMObjectPage.onForm({ section: "itemgeninfo" }).iCheckField({ property: "Reqdqty" });
            Then.onTheZP_ZSOR_ITMObjectPage.onForm({ section: "itemgeninfo" }).iCheckField({ property: "Requnit" });
            Then.onTheZP_ZSOR_ITMObjectPage.onForm({ section: "itemgeninfo" }).iCheckField({ property: "Reqdelvdate" });
            Then.onTheZP_ZSOR_ITMObjectPage.onForm({ section: "itemgeninfo" }).iCheckField({ property: "Materialbycustomer" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});