/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZP_ZSOR_HDRObjectPageObjectPage journey");

        opaTest("Navigate to ZP_ZSOR_HDRObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZP_ZSOR_HDRList.onFilterBar().iExecuteSearch();

            Then.onTheZP_ZSOR_HDRList.onTable().iCheckRows();
            When.onTheZP_ZSOR_HDRList.onTable().iPressRow(0);

            Then.onTheZP_ZSOR_HDRObjectPage.iSeeThisPage();
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheZP_ZSOR_HDRObjectPage.onHeader().iCheckHeaderFacet({ facetId: "HeaderFacetParent" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZP_ZSOR_HDRObjectPage.iCheckNumberOfSections(3);
            When.onTheZP_ZSOR_HDRObjectPage.iPressSectionIconTabFilterButton("Geninfo");
            Then.onTheZP_ZSOR_HDRObjectPage.iCheckSection({ section: "Geninfo" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Geninfo" }).iCheckField({ property: "Sor" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Geninfo" }).iCheckField({ property: "Vbeln" });
            When.onTheZP_ZSOR_HDRObjectPage.iPressSectionIconTabFilterButton("Header");
            Then.onTheZP_ZSOR_HDRObjectPage.iCheckSection({ section: "Header" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Kunag" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Kunwe" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Vkorg" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Vtweg" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Spart" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Netwr" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Waerk" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Bstkd" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Soldtoadrnr" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Shiptoadrnr" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Contract" });
            Then.onTheZP_ZSOR_HDRObjectPage.onForm({ section: "Header" }).iCheckField({ property: "Quote" });
            When.onTheZP_ZSOR_HDRObjectPage.iPressSectionIconTabFilterButton("Item");
            Then.onTheZP_ZSOR_HDRObjectPage.iCheckSection({ section: "Item" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});